[Definition]
actionstart =
actionstop =
actioncheck =

actionban = echo "<ip> 1;" >> /home/ubuntu/project-root/nginx/banned.conf
            /usr/bin/docker exec rk-nginx nginx -s reload

actionunban = tmp=$(mktemp) && { grep -v "^<ip> 1;$" /home/ubuntu/project-root/nginx/banned.conf > "$tmp" || true; } && cat "$tmp" > /home/ubuntu/project-root/nginx/banned.conf && rm "$tmp"
              /usr/bin/docker exec rk-nginx nginx -s reload

[Init]
name = nginx-ban
