[nginx-login]
enabled   = true
filter    = nginx-login
action    = nginx-ban
            rk-telegram[name=nginx-login]
logpath   = /home/ubuntu/project-root/logs/nginx/access.log
backend   = polling
maxretry  = 5
findtime  = 300
bantime   = 5
ignoreip  = 127.0.0.1/8 ::1
